name: mobile_assignment
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  file_picker: ^10.3.2
  flutter:
    sdk: flutter
  image_picker: ^1.2.0
  signature: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/image_icon.png
    - assets/more_icon.png
