// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZLGcIVbd7cokugUterMVFIQorlKNw6jg',
    appId: '1:129070112093:web:24cc9b5e0decb0df869cb4',
    messagingSenderId: '129070112093',
    projectId: 'mobile-assignment-f9fab',
    authDomain: 'mobile-assignment-f9fab.firebaseapp.com',
    storageBucket: 'mobile-assignment-f9fab.firebasestorage.app',
    measurementId: 'G-NSBVGLJMJZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmzmd0Ql1KbpiRUlGH3lVmXOR8aj62J-g',
    appId: '1:129070112093:android:9e5141a2f1ef31b6869cb4',
    messagingSenderId: '129070112093',
    projectId: 'mobile-assignment-f9fab',
    storageBucket: 'mobile-assignment-f9fab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBG6GZzJp35r1_jo6d9v5aiGTtAEkcO3Es',
    appId: '1:129070112093:ios:edb43ff7fd490fe6869cb4',
    messagingSenderId: '129070112093',
    projectId: 'mobile-assignment-f9fab',
    storageBucket: 'mobile-assignment-f9fab.firebasestorage.app',
    iosBundleId: 'com.greenstem.swiftparts.mobileAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBG6GZzJp35r1_jo6d9v5aiGTtAEkcO3Es',
    appId: '1:129070112093:ios:edb43ff7fd490fe6869cb4',
    messagingSenderId: '129070112093',
    projectId: 'mobile-assignment-f9fab',
    storageBucket: 'mobile-assignment-f9fab.firebasestorage.app',
    iosBundleId: 'com.greenstem.swiftparts.mobileAssignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZLGcIVbd7cokugUterMVFIQorlKNw6jg',
    appId: '1:129070112093:web:61964980d85a2816869cb4',
    messagingSenderId: '129070112093',
    projectId: 'mobile-assignment-f9fab',
    authDomain: 'mobile-assignment-f9fab.firebaseapp.com',
    storageBucket: 'mobile-assignment-f9fab.firebasestorage.app',
    measurementId: 'G-KB9LVQ9QXC',
  );

}